CC = g++
FLAGS = -std=c++17 -O3 -Wextra -Wall -Werror -Wno-sign-compare -Wno-unused-result -pedantic
OUTPUT = solution

all: main

main:
	$(CC) $(FLAGS) main.cpp -o $(OUTPUT) -g

clean:
	rm -rf $(OUTPUT)